services:
  - type: web
    name: football-tournament
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py migrate && gunicorn wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.11